version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      TRIGGER_TYPE: <<pipeline.trigger_parameters.circleci.trigger_type>>
    steps:
      - when:
          condition:
            equal: [<< parameters.trigger_parameters.circleci.trigger_type >>, "gitlab"]
          steps:
            - run:
                command: ggshield secret scan -v ci
                environment:
                  CIRCLE_COMMIT_COUNT: << pipeline.trigger_parameters.gitlab.total_commits_count >>
      - when:
          condition:
            equal: [<< parameters.trigger_parameters.circleci.trigger_type >>, "github_app"]
          steps:
            - run:
                command: ggshield secret scan -v ci


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
