version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          if [ "<<pipeline.project.type>>" == "github" ]; then
            echo "export COMMIT_COUNT=<<pipeline.trigger_parameters.github_app.total_commits_count>>" >> $BASH_ENV
          elif [ "<<pipeline.project.type>>" == "gitlab" ]; then
            echo "export COMMIT_COUNT=5" >> $BASH_ENV
          else
            echo "export COMMIT_COUNT=1" >> $BASH_ENV
          fi
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
