version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Determine count"
          command: |
            if [ -n "<<pipeline.trigger_parameters.github_app.total_commits_count>>" ]; then
              echo "export COMMIT_COUNT=<<pipeline.trigger_parameters.github_app.total_commits_count>>" >> $BASH_ENV
            elif [ -n "<<pipeline.trigger_parameters.gitlab.total_commits_count>>" ]; then
              echo "export COMMIT_COUNT=<<pipeline.trigger_parameters.gitlab.total_commits_count>>" >> $BASH_ENV
            else
              echo "Neither GitHub nor GitLab commit count is available."
              exit 1
            fi
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
