version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      TRIGGER_TYPE: <<pipeline.trigger_parameters.circleci.trigger_type>>
    steps:
      - checkout
      - run:
          name: "Set CIRCLE_COMMIT_COUNT based on trigger type"
          command: |
            export CIRCLE_COMMIT_COUNT=$(echo "${pipeline.trigger_parameters.circleci.trigger_type}" == "gitlab" && echo "${pipeline.trigger_parameters.gitlab.total_commits_count}" || echo "${pipeline.trigger_parameters.github_app.total_commits_count}")
      - run:
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
