version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition:
            equal: [<<pipeline.trigger_parameters.circleci.trigger_type>>, "gitlab"]
          steps:
            - run:
                command: env
                environment:
                  CIRCLE_COMMIT_COUNT: << pipeline.trigger_parameters.gitlab.total_commits_count >>
      - when:
          condition:
            equal: [<<pipeline.trigger_parameters.circleci.trigger_type>>, "github_app"]
          steps:
            - run:
                command: env
                environment:
                  CIRCLE_COMMIT_COUNT: << pipeline.trigger_parameters.github_app.total_commits_count >>


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
