version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      COMMIT_COUNT: <<pipeline.trigger_parameters.github_app.total_commits_count>>
    steps:
      - checkout
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
