version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition: <<pipeline.trigger_parameters.github_app.total_commits_count>>
          steps:
            run: echo "export COMMIT_COUNT=<<pipeline.trigger_parameters.github_app.total_commits_count>>" >> $BASH_ENV
      - unless:
          condition: <<pipeline.trigger_parameters.gitlab.total_commits_count>>
          steps:
            run: echo "export COMMIT_COUNT=<<pipeline.trigger_parameters.gitlab.total_commits_count>>" >> $BASH_ENV
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
