version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      CIRCLE_RANGE: <<pipeline.git.base_revision>>...<<pipeline.git.revision>>
      TRIGGER_TYPE: <<pipeline.trigger_parameters.circleci.trigger_type>>
      EVENT_TYPE: <<pipeline.trigger_parameters.circleci.event_type>>
      GITHUB_APP_CHECKOUT_SHA: <<pipeline.trigger_parameters.github_app.checkout_sha>>
      GITHUB_APP_REF: <<pipeline.trigger_parameters.github_app.ref>>
      GITHUB_APP_COMMIT_SHA: <<pipeline.trigger_parameters.github_app.commit_sha>>
      GITHUB_APP_DEFAULT_BRANCH: <<pipeline.trigger_parameters.github_app.default_branch>>
      GITHUB_APP_BRANCH: <<pipeline.trigger_parameters.github_app.branch>>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "env"


workflows:
  say-hello-workflow:
    jobs:
      - say-hello