version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Determine count"
          command: ./set-commit-count.sh "<< pipeline.project.type >>" "<< pipeline.trigger_parameters.github_app.total_commits_count >>" "<< pipeline.trigger_parameters.gitlab.total_commits_count >>"
      - run:
          name: "Display environment variables"
          command: "env"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
